New keyboard shortcut to commit without pushing
haydenull/logseq-plugin-git pull request #59
Opened 2024-04-12 16:08 UTC by lightproof

Added a keyboard shortcut for commit only (now set to <kbd>alt+shift+s</kbd> by default), in addition to the already existing options. For those cases when Logseq is used with local git.

This partially takes care of #40, albeit manually.

2024-04-25 15:41 UTC, EnderDobra requested changes
Hi.
and additional checkStatus() is needed after operations.commit() to update status indicator.

commit: debounce(async function () {
  hidePopup();
  await commit(true, `[logseq-plugin-git:commit] ${new Date().toISOString()}`);
  checkStatus();
}),

2024-05-03 12:01 UTC, lightproof commented
> An additional checkStatus() is needed

Done

2024-05-04 07:16 UTC, EnderDobra approved these changes
Thanks! 
@haydenull please review.

2024-05-21 06:38 UTC, haydenull commented
Thank you all for your efforts, sorry for the late reply.

2024-05-21 06:39 UTC, merged